apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rkpmzqe41-python 
  janus-idp.io/tekton: rkpmzqe41-python
  backstage.io/kubernetes-id: rkpmzqe41-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rkpmzqe41-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml