apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rkpmzqe41-python
  janus-idp.io/tekton: rkpmzqe41-python
  backstage.io/kubernetes-id: rkpmzqe41-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rkpmzqe41-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
